project:
  type: website
  output-dir: docs
  
website:
  title: "Olivia Boyan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - classes.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/liv1422/mybiowebsite-repo
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Olivia Boyan"

format:
  html:
    theme: Solar
    toc: true

editor: source

