---
title: "Projects"
---

## Respiration Data from Summer Internship

I am currently working with data from my internship with Dr. Jellison's Lab.

## Biotoxicity in Commercially Important Shellfish Undergraduate Internship in Dr. Jellison's Lab

I was an Undergraduate Research Assistant for Hannah Gossner's PhD research project over the summer. This project was investigating the effects of biotoxicity on commercially important bivalve species in varying water conditions relating to climate change. In this position I cared for the lab organisms (bivalves and phytoplankton), cared for the aquaria (Neptune Systems APEX), and collected experimental data (respiration results, pseudo-feces samples, bivalve tissue, water samples, and water parameters).

## Habitat use of New Zealand long-tailed bats (*Chalinolobus tuberculatus*) in a fragmented habitat

I conducted research on New Zealand long-tailed bats as part of my directed research project in my time studying abroad in New Zealand with the EcoQuest Centre for Indigeneity, Ecology and Creativity. Finding Franklin Bats is an ongoing study in Franklin, NZ to understand the ecology of these bats and to educate the public. During my project I created and carried out education plans for primary school children (K-6th). I also participated in field work to locate roosts, track the movement of tagged bats, and deploy acoustic bat monitors (ABMs). After data collection, we presented our findings to the public.

## Undergraduate Research Assistant in Dr. Jellison's Lab

I measured images of Eastern Oyster spat using ImageJ and processed water samples for alkalinity using a Metrohm titrator and Robotic Titrosampler with Tiamo 3.0.

## Characteristics of wild moose (*Alces alces*) vocalizations

I was an Undergraduate Researcher on this project where we collected videos of Moose bulls, cows, and calves vocalizing on YouTube, analyzed them for peak frequency, center frequency, bandwidth, and duration across sex classes. This study was conducted with the intent to develop passive acoustic detection for Moose. This study was published with the title "Characteristics of wild moose (*Alces alces*) vocalizations".

<https://doi.org/10.1121/10.0025465>

## Anthropogenic effects on American Bullfrog vocalizations

I was an Undergraduate Researcher on this project where I used previously collected data on American Bullfrog vocalizations in ponds around Durham, NH. I compared the vocalizations (bandwidth, center frequency, and SNR NIST quick) to the whistle from the train running through the area to investigate if any changes in bullfrog vocalizations occured before, during, and after the train whistle.
